server:
  port: 8102

spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      defaultZone: http://user:Password@localhost:8100/eureka/

feign:
  hystrix:
    enabled: true
