server:
 port: 8101

spring:
 application:
  name: hello-service

eureka:
 client:
  service-url:
   defaultZone: http://user:Password@localhost:8100/eureka/

feign:
 hystrix:
  enabled: true
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 5000
 #  instance:
#    prefer-ip-address: true
#      instance-id:  ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
#      lease-renewal-interval-in-seconds: 10
